//! NPC Bark System - Ambient dialogue when player approaches NPCs
//!
//! Barks are short lines NPCs say when triggered by proximity, events, or conditions.
//! They use templates when AI sidecar is unavailable.

use hecs::World;
use std::collections::HashMap;

use crate::components::*;
use crate::vibecode::Vibecode;
use crate::Entity;

/// Bark trigger types
#[derive(Debug, Clone, PartialEq)]
pub enum BarkTrigger {
    /// Player enters proximity range
    Proximity { radius: f32 },
    /// Time-based (e.g., morning, evening)
    TimeOfDay { hour: u8, minute: u8 },
    /// Specific event occurs
    Event { event_type: String },
    /// Random chance per tick
    Random { chance: f32 },
    /// On interaction
    Interaction,
    /// On combat start
    CombatStart,
    /// On taking damage
    TakeDamage,
}

/// Bark category for templates
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BarkCategory {
    Greeting,
    Danger,
    Weather,
    Trade,
    Lore,
    Combat,
    Idle,
    Farewell,
}

impl BarkCategory {
    /// Get template options for this category
    pub fn templates(&self) -> &'static [&'static str] {
        match self {
            BarkCategory::Greeting => &[
                "Greetings, traveler.",
                "Well met!",
                "Hello there.",
                "Welcome to these parts.",
                "Good day!",
                "*nods*",
            ],
            BarkCategory::Danger => &[
                "Be careful around here.",
                "Danger lurks nearby.",
                "Watch your step.",
                "Stay alert!",
                "You'd best be on guard.",
                "*glances nervously*",
            ],
            BarkCategory::Weather => &[
                "Fine weather we're having.",
                "Storm's coming, I can feel it.",
                "Bit chilly today, isn't it?",
                "Perfect day for traveling.",
                "Hope this rain lets up soon.",
            ],
            BarkCategory::Trade => &[
                "Looking to buy or sell?",
                "Got some fine goods here.",
                "Best prices in town!",
                "What can I get for you?",
                "Fresh stock just arrived.",
            ],
            BarkCategory::Lore => &[
                "They say these ruins are ancient...",
                "Legend speaks of a great treasure.",
                "My grandmother told me stories...",
                "This place has a dark history.",
                "Did you hear about the old well?",
            ],
            BarkCategory::Combat => &[
                "For glory!",
                "You'll not take me alive!",
                "Have at you!",
                "*grunts with effort*",
                "Stand down!",
            ],
            BarkCategory::Idle => &[
                "*hums a tune*",
                "*stretches*",
                "*looks around*",
                "Hmm...",
                "*sighs*",
            ],
            BarkCategory::Farewell => &[
                "Safe travels!",
                "Come back soon.",
                "Farewell!",
                "Until next time.",
                "Watch yourself out there.",
            ],
        }
    }

    /// Get random template for this category
    pub fn random(&self, seed: u64) -> &'static str {
        let templates = self.templates();
        let idx = (seed as usize) % templates.len();
        templates[idx]
    }
}

/// Bark request for AI sidecar
#[derive(Debug, Clone)]
pub struct BarkRequest {
    pub npc_name: String,
    pub npc_role: String,
    pub context: String,
    pub mood: String,
    pub location: Option<String>,
    pub category: BarkCategory,
}

impl BarkRequest {
    /// Create a new bark request
    pub fn new(
        npc_name: impl Into<String>,
        npc_role: impl Into<String>,
        category: BarkCategory,
    ) -> Self {
        Self {
            npc_name: npc_name.into(),
            npc_role: npc_role.into(),
            context: String::new(),
            mood: "neutral".to_string(),
            location: None,
            category,
        }
    }

    /// Set context
    pub fn with_context(mut self, context: impl Into<String>) -> Self {
        self.context = context.into();
        self
    }

    /// Set mood
    pub fn with_mood(mut self, mood: impl Into<String>) -> Self {
        self.mood = mood.into();
        self
    }
}

/// Bark response
#[derive(Debug, Clone)]
pub struct BarkResponse {
    pub text: String,
    pub source: BarkSource,
    pub confidence: f32,
}

/// Source of the bark
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BarkSource {
    /// Generated by AI
    Ai,
    /// Template-based fallback
    Template,
    /// Vibecode-defined
    Vibecode,
}

/// NPC Bark component
#[derive(Debug, Clone)]
pub struct NpcBark {
    /// Last bark time
    pub last_bark_time: f32,
    /// Cooldown between barks (seconds)
    pub cooldown_secs: f32,
    /// Proximity radius for auto-trigger
    pub proximity_radius: f32,
    /// Vibecode reference for personality
    pub vibecode: Option<Vibecode>,
    /// Custom barks from vibecode
    pub custom_barks: HashMap<BarkCategory, Vec<String>>,
    /// Whether bark was triggered this frame
    pub triggered: bool,
    /// Current bark text (if any)
    pub current_bark: Option<String>,
    /// How long current bark has been displayed
    pub bark_display_time: f32,
    /// How long to display barks
    pub bark_duration_secs: f32,
}

impl Default for NpcBark {
    fn default() -> Self {
        Self {
            last_bark_time: -f32::INFINITY,
            cooldown_secs: 30.0,
            proximity_radius: 3.0,
            vibecode: None,
            custom_barks: HashMap::new(),
            triggered: false,
            current_bark: None,
            bark_display_time: 0.0,
            bark_duration_secs: 5.0,
        }
    }
}

impl NpcBark {
    /// Create new NPC bark component
    pub fn new() -> Self {
        Self::default()
    }

    /// Set cooldown
    pub fn with_cooldown(mut self, secs: f32) -> Self {
        self.cooldown_secs = secs;
        self
    }

    /// Set proximity radius
    pub fn with_proximity(mut self, radius: f32) -> Self {
        self.proximity_radius = radius;
        self
    }

    /// Set vibecode
    pub fn with_vibecode(mut self, vibecode: Vibecode) -> Self {
        // Extract custom barks from vibecode
        for greeting in &vibecode.dialogue.greetings {
            self.custom_barks
                .entry(BarkCategory::Greeting)
                .or_default()
                .push(greeting.clone());
        }

        self.vibecode = Some(vibecode);
        self
    }

    /// Check if can bark (cooldown elapsed)
    pub fn can_bark(&self, current_time: f32) -> bool {
        current_time - self.last_bark_time >= self.cooldown_secs
    }

    /// Trigger a bark
    pub fn trigger(&mut self, category: BarkCategory, current_time: f32) -> Option<&str> {
        if !self.can_bark(current_time) {
            return None;
        }

        // Try custom barks first
        if let Some(custom) = self.custom_barks.get(&category) {
            if !custom.is_empty() {
                let idx = (current_time as usize) % custom.len();
                let text = custom[idx].clone();
                self.start_bark(text, current_time);
                return self.current_bark.as_deref();
            }
        }

        // Try vibecode greeting
        if category == BarkCategory::Greeting {
            if let Some(ref vibe) = self.vibecode {
                if let Some(greeting) = vibe.get_greeting() {
                    self.start_bark(greeting.to_string(), current_time);
                    return self.current_bark.as_deref();
                }
            }
        }

        // Fall back to templates
        let text = category.random(current_time as u64).to_string();
        self.start_bark(text, current_time);
        self.current_bark.as_deref()
    }

    /// Start displaying a bark
    fn start_bark(&mut self, text: String, current_time: f32) {
        self.current_bark = Some(text);
        self.bark_display_time = 0.0;
        self.last_bark_time = current_time;
        self.triggered = true;
    }

    /// Update bark display
    pub fn update(&mut self, dt: f32) {
        self.triggered = false;

        if self.current_bark.is_some() {
            self.bark_display_time += dt;

            if self.bark_display_time >= self.bark_duration_secs {
                self.current_bark = None;
                self.bark_display_time = 0.0;
            }
        }
    }

    /// Get current bark text if displaying
    pub fn current_bark(&self) -> Option<&str> {
        self.current_bark.as_deref()
    }

    /// Check if a bark is currently displayed
    pub fn is_displaying(&self) -> bool {
        self.current_bark.is_some()
    }

    /// Clear current bark
    pub fn clear(&mut self) {
        self.current_bark = None;
        self.bark_display_time = 0.0;
    }
}

/// Bark system
pub struct BarkSystem {
    /// Template fallback for when AI is unavailable
    use_templates: bool,
}

impl BarkSystem {
    /// Create new bark system
    pub fn new() -> Self {
        Self {
            use_templates: true,
        }
    }

    /// Set whether to use templates
    pub fn use_templates(mut self, use_templates: bool) -> Self {
        self.use_templates = use_templates;
        self
    }

    /// Update all NPC barks
    pub fn update(&self, world: &mut World, dt: f32, current_time: f32, player_pos: glam::Vec2) {
        // Update bark display times
        for (_, bark) in world.query_mut::<&mut NpcBark>() {
            bark.update(dt);
        }

        // Check proximity triggers
        for (_, (pos, bark)) in world.query_mut::<(&Position, &mut NpcBark)>() {
            if bark.triggered {
                continue; // Already triggered this frame
            }

            let npc_pos = glam::Vec2::new(pos.x as f32, pos.y as f32);
            let distance = (npc_pos - player_pos).length();

            // Check if player entered proximity and can bark
            if distance <= bark.proximity_radius && bark.can_bark(current_time) {
                // Use greeting category for proximity
                bark.trigger(BarkCategory::Greeting, current_time);
            }
        }
    }

    /// Generate a bark using templates (offline fallback)
    pub fn generate_template_bark(&self, request: &BarkRequest) -> BarkResponse {
        let text = request
            .category
            .random(request.npc_name.len() as u64)
            .to_string();

        BarkResponse {
            text,
            source: BarkSource::Template,
            confidence: 0.8,
        }
    }

    /// Generate a bark from vibecode
    pub fn generate_vibecode_bark(
        &self,
        vibecode: &Vibecode,
        category: BarkCategory,
    ) -> Option<BarkResponse> {
        match category {
            BarkCategory::Greeting => vibecode.get_greeting().map(|text| BarkResponse {
                text: text.to_string(),
                source: BarkSource::Vibecode,
                confidence: 0.9,
            }),
            BarkCategory::Farewell => vibecode.get_farewell().map(|text| BarkResponse {
                text: text.to_string(),
                source: BarkSource::Vibecode,
                confidence: 0.9,
            }),
            _ => None,
        }
    }
}

impl Default for BarkSystem {
    fn default() -> Self {
        Self::new()
    }
}

/// Bark UI display information
#[derive(Debug, Clone)]
pub struct BarkDisplay {
    pub text: String,
    pub npc_name: String,
    pub position: glam::Vec2,
    pub alpha: f32,
    pub duration: f32,
    pub elapsed: f32,
}

impl BarkDisplay {
    /// Create new bark display
    pub fn new(text: impl Into<String>, npc_name: impl Into<String>, position: glam::Vec2) -> Self {
        Self {
            text: text.into(),
            npc_name: npc_name.into(),
            position,
            alpha: 1.0,
            duration: 5.0,
            elapsed: 0.0,
        }
    }

    /// Update display
    pub fn update(&mut self, dt: f32) {
        self.elapsed += dt;

        // Fade out in last second
        let remaining = self.duration - self.elapsed;
        if remaining <= 1.0 {
            // Scale so that alpha is slightly less than 1.0 when fading starts
            self.alpha = (remaining * 0.99).max(0.0);
        }
    }

    /// Check if display is complete
    pub fn is_complete(&self) -> bool {
        self.elapsed >= self.duration
    }

    /// Get display progress (0.0 to 1.0)
    pub fn progress(&self) -> f32 {
        (self.elapsed / self.duration).min(1.0)
    }
}

/// Collect all active barks for rendering
pub fn collect_active_barks(world: &World) -> Vec<(Entity, String)> {
    let mut barks = vec![];

    for (entity, bark) in world.query::<&NpcBark>().iter() {
        if let Some(text) = bark.current_bark() {
            barks.push((entity, text.to_string()));
        }
    }

    barks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bark_category() {
        let greeting = BarkCategory::Greeting;
        let text = greeting.random(42);
        assert!(!text.is_empty());
        assert!(text.len() <= 80);
    }

    #[test]
    fn test_npc_bark() {
        let mut bark = NpcBark::new().with_cooldown(1.0).with_proximity(3.0);

        assert!(bark.can_bark(0.0));

        bark.trigger(BarkCategory::Greeting, 0.0);
        assert!(bark.is_displaying());

        assert!(!bark.can_bark(0.5)); // Still in cooldown
        assert!(bark.can_bark(1.5)); // Cooldown elapsed
    }

    #[test]
    fn test_bark_display() {
        let mut display = BarkDisplay::new("Hello!", "NPC", glam::Vec2::ZERO);

        assert!(!display.is_complete());

        display.update(4.0);
        assert!(!display.is_complete());
        assert!(display.alpha < 1.0); // Should be fading

        display.update(2.0);
        assert!(display.is_complete());
    }
}
