//! Document Templates
//!
//! Templates for generating various documentation formats.

use std::collections::HashMap;

/// Markdown template for World Bible
pub const WORLD_BIBLE_TEMPLATE: &str = r#"# {title} - World Bible

> Generated: {generated_at}

## Table of Contents
1. [Lore & Mythology](#lore)
2. [Timeline](#timeline)
3. [Geography](#geography)
4. [Factions](#factions)
5. [Characters](#characters)

---

## Lore & Mythology

### Creation Myth
{creation_myth}

### Historical Events
{history}

### Cultural Practices
{culture}

---

## Timeline

{timeline}

---

## Geography

{geography}

---

## Factions

{factions}

---

## Notable Characters

{characters}

---

*Generated by DocDamage Engine Auto-Documentation*
"#;

/// Template for individual character profile
pub const CHARACTER_TEMPLATE: &str = r#"## {name}

### Physical Description
{physical_description}

### Personality
{personality}

### Background
{background}

### Motivations
{motivations}

### Relationships
{relationships}

### AI Portrait Prompt
```
{portrait_prompt}
```
"#;

/// Template for quest log
pub const QUEST_LOG_TEMPLATE: &str = r#"# Quest Log - {project_name}

## Story Arcs

{story_arcs}

## All Quests

{quests}
"#;

/// Template for store description
pub const STORE_DESCRIPTION_TEMPLATE: &str = r#"# {project_name} - Store Page

## Short Description
{short_description}

## Full Description
{full_description}

## Key Features
{key_features}

## Target Audience
{target_audience}

---
*Generated by DocDamage Engine*
"#;

/// Document template engine
pub struct TemplateEngine;

impl TemplateEngine {
    /// Render template with data
    pub fn render(template: &str, data: &HashMap<String, String>) -> String {
        let mut result = template.to_string();
        for (key, value) in data {
            result = result.replace(&format!("{{{}}}", key), value);
        }
        result
    }

    /// Render template with simple key-value pairs
    pub fn render_simple(template: &str, pairs: &[(&str, &str)]) -> String {
        let mut result = template.to_string();
        for (key, value) in pairs {
            result = result.replace(&format!("{{{}}}", key), value);
        }
        result
    }
}

/// Document template trait
pub trait DocumentTemplate {
    /// Render the template to string
    fn render(&self) -> String;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_engine_render() {
        let mut data = HashMap::new();
        data.insert("title".to_string(), "My RPG".to_string());
        data.insert("generated_at".to_string(), "2024-01-01".to_string());

        let template = "# {title}\n\nGenerated: {generated_at}";
        let result = TemplateEngine::render(template, &data);

        assert!(result.contains("# My RPG"));
        assert!(result.contains("Generated: 2024-01-01"));
    }

    #[test]
    fn test_template_engine_render_simple() {
        let template = "Hello, {name}! Welcome to {place}.";
        let result = TemplateEngine::render_simple(template, &[("name", "Alice"), ("place", "Wonderland")]);

        assert_eq!(result, "Hello, Alice! Welcome to Wonderland.");
    }

    #[test]
    fn test_world_bible_template_structure() {
        assert!(WORLD_BIBLE_TEMPLATE.contains("{title}"));
        assert!(WORLD_BIBLE_TEMPLATE.contains("{creation_myth}"));
        assert!(WORLD_BIBLE_TEMPLATE.contains("{timeline}"));
        assert!(WORLD_BIBLE_TEMPLATE.contains("{factions}"));
    }

    #[test]
    fn test_character_template_structure() {
        assert!(CHARACTER_TEMPLATE.contains("{name}"));
        assert!(CHARACTER_TEMPLATE.contains("{physical_description}"));
        assert!(CHARACTER_TEMPLATE.contains("{personality}"));
        assert!(CHARACTER_TEMPLATE.contains("{portrait_prompt}"));
    }
}
