//! Standalone Runtime Export
//!
//! Export for DDE standalone runtime distribution.

use serde::{Deserialize, Serialize};

/// Standalone game configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StandaloneGameConfig {
    pub title: String,
    pub version: String,
    #[serde(rename = "windowWidth")]
    pub window_width: u32,
    #[serde(rename = "windowHeight")]
    pub window_height: u32,
    #[serde(rename = "targetFps")]
    pub target_fps: u32,
    pub vsync: bool,
}

impl Default for StandaloneGameConfig {
    fn default() -> Self {
        Self {
            title: "My Game".to_string(),
            version: "1.0.0".to_string(),
            window_width: 1280,
            window_height: 720,
            target_fps: 60,
            vsync: true,
        }
    }
}

/// Standalone export builder
pub struct StandaloneExporter {
    config: StandaloneGameConfig,
}

impl StandaloneExporter {
    pub fn new(config: StandaloneGameConfig) -> Self {
        Self { config }
    }

    pub fn generate_game_json(&self) -> String {
        serde_json::to_string_pretty(&self.config).unwrap_or_default()
    }

    pub fn generate_readme(&self, project_name: &str) -> String {
        format!(
            r#"# {}

Generated by DocDamage Engine v{}

## Running the Game

### Windows
Double-click `{}.exe` or run from command line.

### macOS
Open `{}.app` or run `./{}` from terminal.

### Linux
Run `./{}` from terminal.

## Configuration

Edit `data/game.json` to change:
- Window resolution
- Target frame rate
- VSync settings

## Support

For help, visit: https://github.com/docsrpg/dde
"#,
            project_name,
            self.config.version,
            project_name.to_lowercase(),
            project_name,
            project_name.to_lowercase(),
            project_name.to_lowercase(),
        )
    }
}
